### ISSUE TITLE
The `divider_top` and `divider_bottom` look too thick in dark theme

### ISSUE THREAD

**Issue by trietbui85** [skydoves/Needs#2]
**Is your feature request related to a problem?**

The `divider_top` and `divider_bottom` are too thick in dark theme although it's just 1 dp (but in light theme it seems fine).

**Describe the solution you'd like:**

Could we set its default height to 1 pixel instead?

**Comment by skydoves** [comment]
@anticafe 
Thank you for your issue.
I agree with your opinion.
It will be added setDividerHeight builder method on next version.

**Comment by skydoves** [comment]
@anticafe 
It's released version `1.0.1`.
Thank you for your issue!
