### ISSUE TITLE
In landscape mode, popup does not show button to grant permissions 

### ISSUE THREAD

**Issue by ghost** [skydoves/Needs#4]
**Please complete the following information:**
- Library Version: 1.0.1
- Affected Device(s): Samsung Galaxy s8 with Android 9.0
 
**Describe the Bug:**

When changing orientation to landscape (or starting in landscape mode), the list of permissions is displayed but the button not. Probably it goes behind the viewport or something.

**Expected Behavior:**

The button and the complete list of permissions should be shown properly on landscape mode, too. Perhaps a ScrollView would be needed, and a layout for the landscape orientation. I would try to do one, if PR are allowed

**Comment by skydoves** [comment]
@bmalex88 
It is changed on version `1.0.2`.
Thank you for your issue!
