### ISSUE TITLE
Show Dialog

### ISSUE THREAD

**Issue by Okami-x-Senpai** [skydoves/Needs#5]
How can I display the dialog without the need for a button?

**Comment by skydoves** [comment]
@Okami-x-Senpai 
I can implement it on next version.
But how would you close the popup if there is no close button?

**Comment by Okami-x-Senpai** [comment]
My idea is to show the dialog when they do not accept the permissions, but I see that it needs a View, so that prevents me from showing it in an Android permission verification function.

**Comment by skydoves** [comment]
@Okami-x-Senpai 
It is published version `1.0.3`.
You can make the `confirm` button invisible using the below method.
```java
setConfirmVisible(false)
```
Thank you for your issue!

**Comment by Okami-x-Senpai** [comment]
With this new version I can show the dialog if I need to establish a Víew to the code myDialog.show(view);?

**Comment by skydoves** [comment]
@Okami-x-Senpai 
LoL.. I misunderstood the button meaning.
I thought the button means the `confirm` button.
You can show the popup after finish the inflating layout using the below codes.

```kotlin
    layout.viewTreeObserver.addOnGlobalLayoutListener {
      needs.show(layout)
    }
```

**Comment by Okami-x-Senpai** [comment]
Thanks, but also the new update is very good, thank you ♥ ️

**Comment by Okami-x-Senpai** [comment]
But it would also be great to show it without needing a View in the .show(); method, just like other implementations do.

**Comment by skydoves** [comment]
@Okami-x-Senpai 
Thank you for your issue!
