### ISSUE TITLE
The background of the dialog can not be changed

### ISSUE THREAD

**Issue by Okami-x-Senpai** [skydoves/Needs#6]
I'm trying to **change the background**  of the dialog with the **setBackgroundColor()**  method but it **does not do anything** , try **several methods to get the color**  but the **dialog continues to show the default color** , the white _background color_ . 

I'm using:
- Android Studio 3.4.2
- Java Language
- Gradle 3.4.2

Help me please.

**Comment by skydoves** [comment]
@Okami-x-Senpai 
Hi,
`setBackgroundColor` is not change background of the dialog.
You can change the dialog's background color using like this:
```kotlin
 val theme = needsTheme(baseContext) {
      // this is background of the dialog
      backgroundColor = ContextCompat.getColor(baseContext, R.color.background)
      titleTextForm = textForm(baseContext) {
        textSize = 18
        textColor = ContextCompat.getColor(baseContext, R.color.white)
      }
      descriptionTextForm = textForm(baseContext) {
        textSize = 12
        textColor = ContextCompat.getColor(baseContext, R.color.description)
      }
    }
```

And apply the Needs theme like this!
```kotlin
Needs.Builder(baseContext)
    .setNeedsTheme(theme)
    ....
```

If you can't solve the problem using the solution, let me know.
Thank you.

**Comment by Okami-x-Senpai** [comment]
So what does this method do?

**Comment by skydoves** [comment]
@Okami-x-Senpai 
`setBackgroundColor`changes outside background of the dialog.
I think it seems to be misunderstood easily because of the method name.
Thank you for your issue!

**Comment by Okami-x-Senpai** [comment]
Thank you. :wink:
