### ISSUE TITLE
About the popup window color

### ISSUE THREAD

**Issue by LaNYGG** [skydoves/Needs#7]
Thank you Jaewoong, I love your popup view very much.

But I want to know how can I change the popup window color??

When I use setBackgroundColor, it just changes the color that shows behind. ( I haven't use the DarkNeedsFactory because I don't how to use it )

**Comment by skydoves** [comment]
@LaNYGG 
Hi, thank you for your compliments!
You can change the popup color using below functionalities.

```kotlin
    val theme = needsTheme(context) {
      backgroundColor = ContextCompat.getColor(context, R.color.background)
      titleTextForm = textForm(context) {
        textSize = 18
        textColor = ContextCompat.getColor(context, R.color.white)
      }
      descriptionTextForm = textForm(context) {
        textSize = 12
        textColor = ContextCompat.getColor(context, R.color.description)
      }
    }

// sets the needs theme
needs.setNeedsTheme(theme)
```

The `DarkNeedsFactory` can be used as below.
```kotlin
private val needs_dark by needs(DarkNeedsFactory::class)
```

You can initialize an instance of the needs popup simply using `by needs` keyword with your customized Factory class.
